//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap I0 {
            get {
                object obj = ResourceManager.GetObject("I0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap I1 {
            get {
                object obj = ResourceManager.GetObject("I1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap I2 {
            get {
                object obj = ResourceManager.GetObject("I2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap I3 {
            get {
                object obj = ResourceManager.GetObject("I3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap parchment {
            get {
                object obj = ResourceManager.GetObject("parchment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pbg {
            get {
                object obj = ResourceManager.GetObject("Pbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El aire estaba llena de humo, es difficil respirar con tanta contaminacion, grandes nubles de ceniza y vapor cubrian al barco en su enteridad, llegando hasta la caja en la que me escondia
        ///#Pronto oi un silbato, por mientras que el gran barco volador empezo a decender.el llanto del oceano fue remplazado por la harmonia de la cuidad.
        ///#una vez en el puerto, dos rufianes levantaron mi escondite y se lo llevaron,evadiendo ala policia, pusieron mi caja en un caruage y empezaron a manejar.
        ///#Apesar de estar en la c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S1 {
            get {
                return ResourceManager.GetString("S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..................................
        ///#Es el año 2058, Tuviste una noche pesada como detective privado en Liverpool, Inglaterra.
        ///En eso tocan a tu puerta. 
        ///#Al parecer alguien asesino a tu hermana en Londres esa misma noche. 
        ///Y aquí es donde empieza el juego.
        ///#Llegas al cuarto donde fue asesinada, es un cuarto chico, alfombra morada
        ///una mesita y la cama. Al fondo esta la puerta para ir al baño.
        ///#Es un cuarto elegante, alamenos para estar en una prision
        ///#Nunca estuve cerca con mi hermana, Me fui de la hacienda  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S2 {
            get {
                return ResourceManager.GetString("S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Te encuentras en la calle. Muy pocas pistas. -Quien sera el asesino?
        ///#Un kinder sorpresa? me estara jodiendo el maldito?-.Tienes muy pocas pistas, pero
        ///#tienes algo en mente atrapar al desgraciado que asesino a tu hermana.
        ///#Haces un conteo de lo que tienes. 500 libras y una revolver de 3 tiros.
        ///(Para acceder a la bolsa presiona 3 en cualquier momento del juego)
        ///#Tu presision siempre fue certera y presisa asi que cada bala cuenta.
        ///#Choca contio una mujer guapa, quiza 30 años, vestida con falda corta y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S3 {
            get {
                return ResourceManager.GetString("S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Me acerce al &quot;don&quot;, esta tiezo
        ///# &quot;DEjEme ver el cuerpo&quot;
        ///#Don: 
        ///&quot;Alex, tranquilizate&quot;
        ///Se pone enfrente de mi, bloqueando la puerta.
        ///#&quot;Por un demonio, Don, si no me dejas entrar ahi en los siguientes 10 segundos&quot;
        ///Empeze a desenfundar mi arma.
        ///#El simple mente se quedo quieto, sin decir una sola palabra
        ///#Don:
        ///&quot;Se que es difficil, pero necesitamos saber que es lo que tenemos en las manos&quot;
        ///#&quot;Nunca habiamos visto un crimen asi, solo encontramos sus extremidades, el cuerpo no esta&quot;
        ///-El asesinato fue cometido a la [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S4 {
            get {
                return ResourceManager.GetString("S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Dan la vuelta a la esquina, tu mano siempre esta rosando el arma, sabes que debes
        ///#ser precavido. Alguien te estaba cazando y tu estasbas dispuesto a terminar con esta
        ///#mierda. Al dar la vuelta la mujere te detiene y te dice
        ///#-Tengo informacion que recolecto de los barrios bajos, concí a tu hermana hace mucho tiempo.
        ///#Al parecer ella sentía que la seguian, se sentia asustada, siento mucho su perdida-
        ///#(Tu hermana siempre fue igual que ti fría y desconfiada a si que hay algo en esa historia
        ///que no te  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S5 {
            get {
                return ResourceManager.GetString("S5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #-Al parecer algun demente esta detras de ti, pero tiene el poder de convencer a todos
        ///#a estar en su causa, tiene mucho dinero para convencerlos, incluso a los policias-
        ///#señalando a la ventana donde se encuentra la cabeza del jefe- tendria mucho cuidado si fuera tu
        ///#sobre con quien te estas enfrentado, y ten encuenta que no todo son quien dicen ser-
        ///La mujer se marcha sin dejar rasto alguno de que estuviera ahi.
        ///Te quedas analisando, quien te podra odiar tanto?, en el fondo te dices, quien no?
        ///#Solo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S6 {
            get {
                return ResourceManager.GetString("S6", resourceCulture);
            }
        }
    }
}
